Added some tests for settings->password, added new getters and method…
michael120288/LocalCoding21802 pull request #9
Opened 2021-04-30 12:19 UTC by somalil

…s in portal.page.js and settingsPage.js

2021-05-01 01:40 UTC, michael120288 commented on test/pageobjects/portal/settingsPage.js
>  export default new SettingsPage();
Looks very great, but you need to add one more line)

2021-05-01 01:47 UTC, michael120288 commented on test/specs/dropDownMenu/settings/password.spec.js
> +    xdescribe('Toggle visibility icon functional', () => {
is it a mistake or it is suppose to be like this? (xdescribe =  describe)

2021-05-01 01:51 UTC, michael120288 requested changes
just couple adjustment need

2021-05-01 10:53 UTC, somalil commented on test/specs/dropDownMenu/settings/password.spec.js
> +    xdescribe('Toggle visibility icon functional', () => {
xdescribe = describe.skip

2021-05-02 08:44 UTC, somalil commented
Changes added, please approve.

2021-05-06 18:13 UTC, michael120288 approved these changes

2021-05-06 18:17 UTC, merged